spring:
  application:
    name: mailapi

  mail:
    host: smtp.gmail.com
    port: 587
    username: Your_Email_ID
    password: Your_PWD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true